#ifndef ONVIF_H
#define ONVIF_H

const char* deviceHeader = 
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" "
  "xmlns:tt=\"http://www.onvif.org/ver10/schema\" "
  "xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\">";

const char* mediaHeader = 
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" "
  "xmlns:tt=\"http://www.onvif.org/ver10/schema\" "
  "xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\">";

const char* discoverNS = 
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" "
  "xmlns:tt=\"http://www.onvif.org/ver10/schema\" "
  "xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" "
  "xmlns:enc=\"http://www.w3.org/2003/05/soap-encoding\" "
  "xmlns:wsa=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" "
  "xmlns:wsa5=\"http://www.w3.org/2005/08/addressing\" "
  "xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" "
  "xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\">";

const char* allHeader =
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" "
  "xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" "
  "xmlns:tt=\"http://www.onvif.org/ver10/schema\" "
  "xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" "
  "xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" "
  "xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" "
  "xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" "
  "xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" "
  "xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" "
  "xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\">";

const char* maxHeader = 
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" "
  "xmlns:e=\"http://www.w3.org/2003/05/soap-encoding\" "
  "xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" "
  "xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" "
  "xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
  "xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" "
  "xmlns:wsnt=\"http://docs.oasis-open.org/wsn/b-2\" "
  "xmlns:wstop=\"http://docs.oasis-open.org/wsn/t-1\" "
  "xmlns:wsntw=\"http://docs.oasis-open.org/wsn/bw-2\" "
  "xmlns:wsrf-rw=\"http://docs.oasis-open.org/wsrf/rw-2\" "
  "xmlns:wsrf-r=\"http://www.onvif.org/ver10/schema/wsrf-r-2\" "
  "xmlns:wsrf-bf=\"http://docs.oasis-open.org/wsrf/bf-2\" "
  "xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl\" "
  "xmlns:wsoap12=\"http://schemas.xmlsoap.org/wsdl/soap12\" "
  "xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http\" "
  "xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" "
  "xmlns:wsadis=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" "
  "xmlns:tt=\"http://www.onvif.org/ver10/schema\" "
  "xmlns:tns1=\"http://www.onvif.org/ver10/topics\" "
  "xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" "
  "xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" "
  "xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" "
  "xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" "
  "xmlns:tst=\"http://www.onvif.org/ver10/storage/wsdl\" "
  "xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" "
  "xmlns:pt=\"http://www.onvif.org/ver10/pacs\" "
  "xmlns:tr2=\"http://www.onvif.org/ver20/media/wsdl\" "
  "xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" "
  "xmlns:tan=\"http://www.onvif.org/ver20/analytics/wsdl\" "
  "xmlns:axt=\"http://www.onvif.org/ver20/analytics\" "
  "xmlns:trp=\"http://www.onvif.org/ver10/replay/wsdl\" "
  "xmlns:tse=\"http://www.onvif.org/ver10/search/wsdl\" "
  "xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" "
  "xmlns:tac=\"http://www.onvif.org/ver10/accesscontrol/wsdl\" "
  "xmlns:tdc=\"http://www.onvif.org/ver10/doorcontrol/wsdl\" "
  "xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\" "
  "xmlns:tth=\"http://www.onvif.org/ver10/thermal/wsdl\" "
  "xmlns:tcr=\"http://www.onvif.org/ver10/credential/wsdl\" "
  "xmlns:tar=\"http://www.onvif.org/ver10/accessrules/wsdl\" "
  "xmlns:tsc=\"http://www.onvif.org/ver10/schedule/wsdl\" "
  "xmlns:trv=\"http://www.onvif.org/ver10/receiver/wsdl\" "
  "xmlns:tpv=\"http://www.onvif.org/ver10/provisioning/wsdl\" "
  "xmlns:ter=\"http://www.onvif.org/ver10/error\">";




const char* footer = 
  "</s:Body></s:Envelope>";

// Discovery
const char* onvifHello = 
  "<s:Header>"
  "<wsa:MessageID>uuid:%s</wsa:MessageID>"
  "<wsa:To>urn:schemas-xmlsoap-org:ws:2005:04/discovery</wsa:To>"
  "<wsa:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Hello</wsa:Action>"
  "</s:Header>"
  "<s:Body>"
  "<d:Hello>"
  "<wsa:EndpointReference>"
  "<wsa:Address>urn:uuid:%s</wsa:Address>"
  "</wsa:EndpointReference>"
  "<d:Types>dn:NetworkVideoTransmitter tds:Device</d:Types>"
  "<d:Scopes>"
  "onvif://www.onvif.org/location/Home "
  "onvif://www.onvif.org/name:%s "
  "onvif://www.onvif.org/hardware:%s "
  "onvif://www.onvif.org/type/audio_encoder "
  "onvif://www.onvif.org/type/video_encoder "
  "onvif://www.onvif.org/type/ptz"
  "</d:Scopes>"
  "<d:XAddrs>http://%s/onvif/device_service</d:XAddrs>"
  "<d:MetadataVersion>1</d:MetadataVersion>"
  "</d:Hello>";

const char* onvifBye = 
  "<s:Header>"
  "<wsa:MessageID>uuid:%s</wsa:MessageID>"
  "<wsa:To>urn:schemas-xmlsoap-org:ws:2005:04/discovery</wsa:To>"
  "<wsa:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Bye</wsa:Action>"
  "</s:Header>"
  "<s:Body>"
  "<d:Bye>"
  "<wsa:EndpointReference>"
  "<wsa:Address>urn:uuid:%s</wsa:Address>"
  "</wsa:EndpointReference>"
  "</d:Bye>";

const char* onvifMatch = 
  "<s:Header>"
  "<wsa:MessageID>uuid:%s</wsa:MessageID>"
  "<wsa:RelatesTo>uuid:%s</wsa:RelatesTo>"
  "<wsa:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To>"
  "<wsa:Action>%s</wsa:Action>"
  "</s:Header>"
  "<s:Body>"
  "<d:%s>"
  "<d:%s>"
  "<wsa:EndpointReference>"
  "<wsa:Address>urn:uuid:%s</wsa:Address>"
  "</wsa:EndpointReference>"
  "<d:Types>dn:NetworkVideoTransmitter tds:Device</d:Types>"
  "<d:Scopes>"
  "onvif://www.onvif.org/location/Home "
  "onvif://www.onvif.org/name:%s "
  "onvif://www.onvif.org/hardware:%s "
  // "onvif://www.onvif.org/type/audio_encoder "
  "onvif://www.onvif.org/type/video_encoder "
  // "onvif://www.onvif.org/type/ptz"
  "</d:Scopes>"
  "<d:XAddrs>http://%s/onvif/device_service</d:XAddrs>"
  "<d:MetadataVersion>1</d:MetadataVersion>"
  "</d:%s>"
  "</d:%s>";

// Device Management
const char* getDeviceInfo = 
  "<s:Body>"
  "<tds:GetDeviceInformationResponse>"
  "<tds:Manufacturer>%s</tds:Manufacturer>"
  "<tds:Model>%s</tds:Model>"
  "<tds:FirmwareVersion>%s</tds:FirmwareVersion>"
  "<tds:SerialNumber>%s</tds:SerialNumber>"
  "<tds:HardwareId>%s</tds:HardwareId>"
  "</tds:GetDeviceInformationResponse>";

// const char* getCapabilities = 
//   "<s:Body>"
//   "<tds:GetCapabilitiesResponse>"
//   "<tds:Capabilities>"
//   "<tds:Device>"
//   "<tds:XAddr>http://%s/onvif/device_service</tds:XAddr>"
//   "</tds:Device>"
//   "<trt:Media>"
//   "<trt:XAddr>http://%s/onvif/media_service</trt:XAddr>"
//   "<trt:StreamingCapabilities>"
//   "<trt:RTPMulticast>false</trt:RTPMulticast>"
//   "<trt:RTP_TCP>false</trt:RTP_TCP>"
//   "<trt:RTP_RTSP_TCP>false</trt:RTP_RTSP_TCP>"
//   "<trt:HttpStreaming>true</trt:HttpStreaming>"
//   "<trt:SessionTimeoutRange>PT10S</trt:SessionTimeoutRange>"
//   "</trt:StreamingCapabilities>"
//   "</trt:Media>"
//   "<tptz:PTZ>"
//   "<tptz:XAddr>http://%s/onvif/ptz_service</tptz:XAddr>"
//   "</tptz:PTZ>"
//   "<timg:Imaging>"
//   "<timg:XAddr>http://%s/onvif/imaging_service</timg:XAddr>"
//   "</timg:Imaging>"
//   "<tev:Event>"
//   "<tev:XAddr>http://%s/onvif/event_service</tev:XAddr>"
//   "</tev:Event>"
//   "<trc:Recording>"
//   "<trc:XAddr>http://%s/onvif/recording_service</trc:XAddr>"
//   "</trc:Recording>"
//   "<d:Discovery>"
//   "<d:XAddr>http://%s/onvif/discovery</d:XAddr>"
//   "</d:Discovery>"
//   "<tds:DeviceDiscovery>"
//   "<tds:XAddr>http://%s/onvif/device_discovery</tds:XAddr>"
//   "</tds:DeviceDiscovery>"
//   "<trt:MediaProfile>"
//   "<trt:XAddr>http://%s/onvif/media_profile</trt:XAddr>"
//   "</trt:MediaProfile>"
//   "<dn:NetworkZeroconf>"
//   "<dn:XAddr>http://%s/onvif/network_zeroconf</dn:XAddr>"
//   "</dn:NetworkZeroconf>"
//   "</tds:Capabilities>"
//   "</tds:GetCapabilitiesResponse>";


const char* getCapabilities = 
  "<s:Body>"
  "<tds:GetCapabilitiesResponse>"
  "<tds:Capabilities>"
  "<tt:Analytics>"
  "<tt:XAddr>http://%s/onvif/analytics_service</tt:XAddr>"
  "<tt:RuleSupport>true</tt:RuleSupport>"
  "<tt:AnalyticsModuleSupport>true</tt:AnalyticsModuleSupport>"
  "</tt:Analytics>"
  "<tt:Device>"
  "<tt:XAddr>http://%s/onvif/device_service</tt:XAddr>"
  "<tt:Network>"
  "<tt:IPFilter>true</tt:IPFilter>"
  "<tt:ZeroConfiguration>true</tt:ZeroConfiguration>"
  "<tt:IPVersion6>false</tt:IPVersion6>"
  "<tt:DynDNS>true</tt:DynDNS>"
  "<tt:Extension>"
  "<tt:Dot11Configuration>true</tt:Dot11Configuration>"
  "</tt:Extension>"
  "</tt:Network>"
  "<tt:System>"
  "<tt:DiscoveryResolve>true</tt:DiscoveryResolve>"
  "<tt:DiscoveryBye>true</tt:DiscoveryBye>"
  "<tt:RemoteDiscovery>false</tt:RemoteDiscovery>"
  "<tt:SystemBackup>true</tt:SystemBackup>"
  "<tt:SystemLogging>true</tt:SystemLogging>"
  "<tt:FirmwareUpgrade>true</tt:FirmwareUpgrade>"
  "<tt:SupportedVersions>"
  "<tt:Major>23</tt:Major><tt:Minor>12</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>23</tt:Major><tt:Minor>6</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>22</tt:Major><tt:Minor>12</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>22</tt:Major><tt:Minor>6</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>21</tt:Major><tt:Minor>12</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>21</tt:Major><tt:Minor>6</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>20</tt:Major><tt:Minor>12</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>20</tt:Major><tt:Minor>6</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>19</tt:Major><tt:Minor>12</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:SupportedVersions>"
  "<tt:Major>2</tt:Major><tt:Minor>0</tt:Minor>"
  "</tt:SupportedVersions>"
  "<tt:Extension>"
  "<tt:HttpFirmwareUpgrade>true</tt:HttpFirmwareUpgrade>"
  "<tt:HttpSystemBackup>true</tt:HttpSystemBackup>"
  "<tt:HttpSystemLogging>true</tt:HttpSystemLogging>"
  "<tt:HttpSupportInformation>true</tt:HttpSupportInformation>"
  "</tt:Extension>"
  "</tt:System>"
  "<tt:IO>"
  "<tt:InputConnectors>1</tt:InputConnectors>"
  "<tt:RelayOutputs>1</tt:RelayOutputs>"
  "<tt:Extension>"
  "<tt:Auxiliary>false</tt:Auxiliary>"
  "<tt:Extension/>"
  "</tt:Extension>"
  "</tt:IO>"
  "<tt:Security>"
  "<tt:TLS1.1>false</tt:TLS1.1>"
  "<tt:TLS1.2>false</tt:TLS1.2>"
  "<tt:OnboardKeyGeneration>false</tt:OnboardKeyGeneration>"
  "<tt:AccessPolicyConfig>true</tt:AccessPolicyConfig>"
  "<tt:X.509Token>false</tt:X.509Token>"
  "<tt:SAMLToken>false</tt:SAMLToken>"
  "<tt:KerberosToken>false</tt:KerberosToken>"
  "<tt:RELToken>false</tt:RELToken>"
  "<tt:Extension>"
  "<tt:TLS1.0>false</tt:TLS1.0>"
  "<tt:Extension>"
  "<tt:Dot1X>true</tt:Dot1X>"
  "<tt:SupportedEAPMethod>0</tt:SupportedEAPMethod>"
  "<tt:RemoteUserHandling>true</tt:RemoteUserHandling>"
  "</tt:Extension>"
  "</tt:Extension>"
  "</tt:Security>"
  "</tt:Device>"
  "<tt:Events>"
  "<tt:XAddr>http://%s/onvif/event_service</tt:XAddr>"
  "<tt:WSSubscriptionPolicySupport>true</tt:WSSubscriptionPolicySupport>"
  "<tt:WSPullPointSupport>true</tt:WSPullPointSupport>"
  "<tt:WSPausableSubscriptionManagerInterfaceSupport>false</tt:WSPausableSubscriptionManagerInterfaceSupport>"
  "</tt:Events>"
  "<tt:Imaging>"
  "<tt:XAddr>http://%s/onvif/image_service</tt:XAddr>"
  "</tt:Imaging>"
  "<tt:Media>"
  "<tt:XAddr>http://%s/onvif/media_service</tt:XAddr>"
  "<tt:StreamingCapabilities>"
  "<tt:RTPMulticast>false</tt:RTPMulticast>"
  "<tt:RTP_TCP>true</tt:RTP_TCP>"
  "<tt:RTP_RTSP_TCP>true</tt:RTP_RTSP_TCP>"
  "</tt:StreamingCapabilities>"
  "<tt:Extension>"
  "<tt:ProfileCapabilities>"
  "<tt:MaximumNumberOfProfiles>10</tt:MaximumNumberOfProfiles>"
  "</tt:ProfileCapabilities>"
  "</tt:Extension>"
  "</tt:Media>"
  "<tt:PTZ>"
  "<tt:XAddr>http://%s/onvif/ptz_service</tt:XAddr>"
  "</tt:PTZ>"
  "<tt:Extension>"
  "<tt:DeviceIO>"
  "<tt:XAddr>http://%s/onvif/deviceio_service</tt:XAddr>"
  "<tt:VideoSources>1</tt:VideoSources>"
  "<tt:VideoOutputs>0</tt:VideoOutputs>"
  "<tt:AudioSources>1</tt:AudioSources>"
  "<tt:AudioOutputs>1</tt:AudioOutputs>"
  "<tt:RelayOutputs>1</tt:RelayOutputs>"
  "</tt:DeviceIO>"
  "<tt:Recording>"
  "<tt:XAddr>http://%s/onvif/recording_service</tt:XAddr>"
  "<tt:ReceiverSource>false</tt:ReceiverSource>"
  "<tt:MediaProfileSource>true</tt:MediaProfileSource>"
  "<tt:DynamicRecordings>true</tt:DynamicRecordings>"
  "<tt:DynamicTracks>true</tt:DynamicTracks>"
  "<tt:MaxStringLength>256</tt:MaxStringLength>"
  "</tt:Recording>"
  "<tt:Search>"
  "<tt:XAddr>http://%s/onvif/search_service</tt:XAddr>"
  "<tt:MetadataSearch>true</tt:MetadataSearch>"
  "</tt:Search>"
  "<tt:Replay>"
  "<tt:XAddr>http://%s/onvif/replay_service</tt:XAddr>"
  "</tt:Replay>"
  "<tt:Receiver>"
  "<tt:XAddr>http://%s/onvif/receiver_service</tt:XAddr>"
  "<tt:RTP_Multicast>true</tt:RTP_Multicast>"
  "<tt:RTP_TCP>true</tt:RTP_TCP>"
  "<tt:RTP_RTSP_TCP>true</tt:RTP_RTSP_TCP>"
  "<tt:SupportedReceivers>10</tt:SupportedReceivers>"
  "<tt:MaximumRTSPURILength>256</tt:MaximumRTSPURILength>"
  "</tt:Receiver>"
  "</tt:Extension>"
  "</tds:Capabilities>"
  "</tds:GetCapabilitiesResponse>";


// const char* getServices = 
//   "<s:Body>"
//   "<tds:GetServicesResponse>"
//   "<tds:Service>"
//   "<tds:Namespace>http://www.onvif.org/ver10/device/wsdl</tds:Namespace>"
//   "<tds:XAddr>http://%s/onvif/device_service</tds:XAddr>"
//   "<tds:Version>"
//   "<tds:Major>2</tds:Major>"
//   "<tds:Minor>0</tds:Minor>"
//   "</tds:Version>"
//   "</tds:Service>"
//   "<tds:Service>"
//   "<tds:Namespace>http://www.onvif.org/ver10/media/wsdl</tds:Namespace>"
//   "<tds:XAddr>http://%s/onvif/media_service</tds:XAddr>"
//   "<tds:Version>"
//   "<tds:Major>2</tds:Major>"
//   "<tds:Minor>0</tds:Minor>"
//   "</tds:Version>"
//   "</tds:Service>"
//   "</tds:GetServicesResponse>";

const char* getServices = 
  "<s:Body>"
  "<tds:GetServicesResponse>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/device/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/device_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>23</tt:Major>"
  "<tt:Minor>12</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/events/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/event_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>22</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver20/media/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/media2_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>23</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/media/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/media_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>22</tt:Major>"
  "<tt:Minor>12</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver20/ptz/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/ptz_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>23</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver20/imaging/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/image_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>22</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver20/analytics/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/analytics_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>23</tt:Major>"
  "<tt:Minor>12</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/recording/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/recording_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>23</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/search/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/search_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>22</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/replay/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/replay_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>21</tt:Major>"
  "<tt:Minor>12</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/accesscontrol/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/accesscontrol_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>21</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/doorcontrol/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/doorcontrol_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>21</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/deviceIO/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/deviceio_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>22</tt:Major>"
  "<tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/thermal/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/thermal_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>22</tt:Major><tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/credential/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/credential_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>21</tt:Major><tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/accessrules/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/accessrules_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>19</tt:Major><tt:Minor>6</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/schedule/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/schedule_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>18</tt:Major><tt:Minor>12</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/receiver/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/receiver_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>21</tt:Major><tt:Minor>12</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "<tds:Service>"
  "<tds:Namespace>http://www.onvif.org/ver10/provisioning/wsdl</tds:Namespace>"
  "<tds:XAddr>http://%s/onvif/provisioning_service</tds:XAddr>"
  "<tds:Version>"
  "<tt:Major>18</tt:Major><tt:Minor>12</tt:Minor>"
  "</tds:Version>"
  "</tds:Service>"
  "</tds:GetServicesResponse>";


const char* getScopes =
  "<s:Body>"
  "<tds:GetScopesResponse>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/type/audio_encoder</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/type/video_encoder</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/type/ptz</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/Profile/Streaming</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/Profile/S</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/Profile/T</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/Profile/G</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/Profile/C</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/Profile/A</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Fixed</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/Profile/M</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Configurable</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/location/Home</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Configurable</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/name/IP-Camera</tt:ScopeItem>"
  "</tds:Scopes>"
  "<tds:Scopes>"
  "<tt:ScopeDef>Configurable</tt:ScopeDef>"
  "<tt:ScopeItem>onvif://www.onvif.org/hardware/HI3518C</tt:ScopeItem>"
  "</tds:Scopes>"
  "</tds:GetScopesResponse>";

const char* getZeroConfig = 
  "<s:Body>"
  "<tds:GetZeroConfigurationResponse>"
  "<tds:ZeroConfiguration>"
  "<tt:InterfaceToken>WiFi</tt:InterfaceToken>"
  "<tt:Enabled>true</tt:Enabled>"
  "<tt:Addresses>"
  "<tt:IPv4Address>%s</tt:IPv4Address>"
  "</tt:Addresses>"
  "</tds:ZeroConfiguration>"
  "</tds:GetZeroConfigurationResponse>";

const char* getNetworkInterfaces =
  "<s:Body>"
  "<tds:GetNetworkInterfacesResponse>"
  "<tds:NetworkInterfaces token=\"NetworkInterfaceToken_1\">"
  "<tt:Enabled>true</tt:Enabled>"
  "<tt:Info>"
  "<tt:Name>WiFi</tt:Name>"
  "<tt:HwAddress>%s</tt:HwAddress>"
  //"<tt:HwAddress>38-00-25-C7-77-A2</tt:HwAddress>"
  "<tt:MTU>1500</tt:MTU>"
  "</tt:Info>"
  "<tt:IPv4>"
  "<tt:Enabled>true</tt:Enabled>"
  "<tt:Config>"
  "<tt:FromDHCP>"
  "<tt:Address>%s</tt:Address>"
  "<tt:PrefixLength>24</tt:PrefixLength>"
  "</tt:FromDHCP>"
  "<tt:DHCP>true</tt:DHCP>"
  "</tt:Config>"
  "</tt:IPv4>"
  "</tds:NetworkInterfaces>"
  "</tds:GetNetworkInterfacesResponse>";

const char* getDNS = 
  "<s:Body>"
  "<tds:GetDNSResponse>"
  "<tds:DNSInformation>"
  "<tt:FromDHCP>false</tt:FromDHCP>"
  "<tt:DNSManual>"
  "<tt:Type>IPv4</tt:Type>"
  "<tt:IPv4Address>192.168.1.1</tt:IPv4Address>" // need to change to pass router address
  "</tt:DNSManual>"
  "</tds:DNSInformation>"
  "</tds:GetDNSResponse>";

const char* getSystemDateAndTime = 
  "<s:Body>"
  "<tds:GetSystemDateAndTimeResponse>"
  "<tds:SystemDateAndTime>"
  "<tds:DateTimeType>NTP</tds:DateTimeType>"
  "<tds:DaylightSavings>false</tds:DaylightSavings>"
  "<tds:TimeZone>"
  "<tds:TZ>CET-1CEST,M3.5.0,M10.5.0/3</tds:TZ>"
  "</tds:TimeZone>"
  "<tds:UTCDateTime>"
  "<tds:Time>"
  "<tds:Hour>10</tds:Hour>"
  "<tds:Minute>0</tds:Minute>"
  "<tds:Second>0</tds:Second>"
  "</tds:Time>"
  "<tds:Date>"
  "<tds:Year>2024</tds:Year>"
  "<tds:Month>10</tds:Month>"
  "<tds:Day>5</tds:Day>"
  "</tds:Date>"
  "</tds:UTCDateTime>"
  "</tds:SystemDateAndTime>"
  "</tds:GetSystemDateAndTimeResponse>";

const char* setSystemDateAndTime = // Not Added Yet !!!
  "<s:Body>"
  "<tds:SetSystemDateAndTimeResponse/>";


// Media services

const char* getProfiles = // Used for both getProfile and getProfile, since we only have 1 we can just reuse this
  "<s:Body>"
  "<trt:Get%sResponse>"
  "<trt:%s token=\"ProfileToken_1\" fixed=\"true\">"
  "<tt:Name>ProfileName_1</tt:Name>"
  "<tt:VideoSourceConfiguration token=\"VideoSourceConfigurationToken_1\">"
  "<tt:Name>VideoSourceConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:SourceToken>VideoSourceToken_1</tt:SourceToken>"
  "<tt:Bounds x=\"0\" y=\"0\" width=\"1280\" height=\"720\"/>"
  "</tt:VideoSourceConfiguration>"
  "<tt:AudioSourceConfiguration token=\"AudioSourceConfigurationToken_1\">"
  "<tt:Name>AudioSourceConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:SourceToken>AudioSourceToken_1</tt:SourceToken>"
  "</tt:AudioSourceConfiguration>"
  "<tt:VideoEncoderConfiguration token=\"VideoEncoderConfigurationToken_1\">"
  "<tt:Name>VideoEncoderConfigurationName_1</tt:Name>"
  "<tt:UseCount>1</tt:UseCount>"
  "<tt:Encoding>JPEG</tt:Encoding>"
  "<tt:Resolution>"
  "<tt:Width>1280</tt:Width>"
  "<tt:Height>720</tt:Height>"
  "</tt:Resolution>"
  "<tt:Quality>4</tt:Quality>"
  "<tt:RateControl>"
  "<tt:FrameRateLimit>25</tt:FrameRateLimit>"
  "<tt:EncodingInterval>1</tt:EncodingInterval>"
  "<tt:BitrateLimit>2048</tt:BitrateLimit>"
  "</tt:RateControl>"
  "<tt:SessionTimeout>PT10S</tt:SessionTimeout>"
  "</tt:VideoEncoderConfiguration>"
  "<tt:AudioEncoderConfiguration token=\"AudioEncoderConfigurationToken_1\">"
  "<tt:Name>AudioEncoderConfigurationName_1</tt:Name>"
  "<tt:UseCount>2</tt:UseCount>"
  "<tt:Encoding>G726</tt:Encoding>"
  "<tt:Bitrate>64000</tt:Bitrate>"
  "<tt:SampleRate>16000</tt:SampleRate>"
  "</tt:AudioEncoderConfiguration>"
  "</trt:%s>"
  "</trt:Get%sResponse>";


const char* getStreamUri = 
  "<s:Body>"
  "<trt:GetStreamUriResponse>"
  "<trt:MediaUri>"
  "<tt:Uri>http://%s/sustain?video=1</tt:Uri>"
  "<tt:InvalidAfterConnect>false</tt:InvalidAfterConnect>"
  "<tt:InvalidAfterReboot>false</tt:InvalidAfterReboot>"
  "<tt:Timeout>PT0S</tt:Timeout>"
  "</trt:MediaUri>"
  "</trt:GetStreamUriResponse>";

const char* getSnapshotUri = 
  "<s:Body>"
  "<trt:GetSnapshotUriResponse>"
  "<trt:MediaUri>"
  "<tt:Uri>http://%s/control?still=1</tt:Uri>"
  "<tt:InvalidAfterConnect>false</tt:InvalidAfterConnect>"
  "<tt:InvalidAfterReboot>false</tt:InvalidAfterReboot>"
  "<tt:Timeout>PT0S</tt:Timeout>"
  "</trt:MediaUri>"
  "</trt:GetSnapshotUriResponse>";

const char* getVideoSources =
  "<s:Body>"
  "<trt:GetVideoSourcesResponse>"
  "<trt:VideoSources token=\"VideoSourceToken_1\">"
  "<tt:Framerate>25.0</tt:Framerate>"
  "<tt:Resolution>"
  "<tt:Width>1280</tt:Width>"
  "<tt:Height>720</tt:Height>"
  "</tt:Resolution>"
  "<tt:Imaging>"
  "<tt:BacklightCompensation>"
  "<tt:Mode>OFF</tt:Mode>"
  "<tt:Level>10.0</tt:Level>"
  "</tt:BacklightCompensation>"
  "<tt:Brightness>50.0</tt:Brightness>"
  "<tt:ColorSaturation>50.0</tt:ColorSaturation>"
  "<tt:Contrast>50.0</tt:Contrast>"
  "<tt:Exposure>"
  "<tt:Mode>AUTO</tt:Mode>"
  "<tt:Priority>LowNoise</tt:Priority>"
  "<tt:Window bottom=\"1.0\" top=\"0.0\" right=\"1.0\" left=\"0.0\"></tt:Window>"
  "<tt:MinExposureTime>10.0</tt:MinExposureTime>"
  "<tt:MaxExposureTime>40000.0</tt:MaxExposureTime>"
  "<tt:MinGain>0.0</tt:MinGain>"
  "<tt:MaxGain>100.0</tt:MaxGain>"
  "<tt:MinIris>0.0</tt:MinIris>"
  "<tt:MaxIris>10.0</tt:MaxIris>"
  "<tt:ExposureTime>4000.0</tt:ExposureTime>"
  "<tt:Gain>100.0</tt:Gain>"
  "<tt:Iris>10.0</tt:Iris>"
  "</tt:Exposure>"
  "<tt:Focus>"
  "<tt:AutoFocusMode>AUTO</tt:AutoFocusMode>"
  "<tt:DefaultSpeed>100.0</tt:DefaultSpeed>"
  "<tt:NearLimit>100.0</tt:NearLimit>"
  "<tt:FarLimit>1000.0</tt:FarLimit>"
  "</tt:Focus>"
  "<tt:IrCutFilter>AUTO</tt:IrCutFilter>"
  "<tt:Sharpness>50.0</tt:Sharpness>"
  "<tt:WideDynamicRange>"
  "<tt:Mode>OFF</tt:Mode>"
  "<tt:Level>50.0</tt:Level>"
  "</tt:WideDynamicRange>"
  "<tt:WhiteBalance>"
  "<tt:Mode>AUTO</tt:Mode>"
  "<tt:CrGain>10.0</tt:CrGain>"
  "<tt:CbGain>10.0</tt:CbGain>"
  "</tt:WhiteBalance>"
  "</tt:Imaging>"
  "</trt:VideoSources>"
  "</trt:GetVideoSourcesResponse>";

const char* getAudioDecoderConfigurations =
  "<s:Body>"
  "<trt:GetAudioDecoderConfigurationsResponse>"
  "<trt:Configurations>"
  "<tt:Name>AudioDecoderConfiguration_1</tt:Name>"
  "<tt:Token>audio_decoder_config_token</tt:Token>"
  "<tt:UseCount>1</tt:UseCount>"
  "</trt:Configurations>"
  "</trt:GetAudioDecoderConfigurationsResponse>";


//Events
const char* createPullPointSubscriptionResponse =
  "<s:Envelope>"
  "<s:Header>"
  "<wsa:MessageID>urn:uuid:%s</wsa:MessageID>"
  "<wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>"
  "<wsa:Action>http://www.onvif.org/ver10/events/wsdl/EventPortType/CreatePullPointSubscriptionResponse</wsa:Action>"
  "</s:Header>"
  "<s:Body>"
  "<tev:CreatePullPointSubscriptionResponse>"
  "<tev:SubscriptionReference>"
  "<wsa:Address>http://%s/event_service/0</wsa:Address>"
  "</tev:SubscriptionReference>"
  "<wsnt:CurrentTime>2024-10-26T03:04:29Z</wsnt:CurrentTime>"
  "<wsnt:TerminationTime>2024-10-26T03:05:29Z</wsnt:TerminationTime>"
  "</tev:CreatePullPointSubscriptionResponse>"
  "</s:Body>"
  "</s:Envelope>";

#endif // ONVIF_H